# Generated by Django 3.2 on 2022-09-03 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='add_to_whishlist',
            field=models.ManyToManyField(blank=True, related_name='whishlist_add', to=settings.AUTH_USER_MODEL),
        ),
    ]
